final List<Map<String, String>> userList = [
  {
    'userId': 'U001',
    'name': 'Alice Johnson',
    'email': 'alice.johnson@example.com',
    'course': 'Computer Science',
    'yearLevel': '3',
    'phoneNumber': '09171234567',
    'status': 'Active',
  },
  {
    'userId': 'U002',
    'name': 'Bob Smith',
    'email': 'bob.smith@example.com',
    'course': 'Information Technology',
    'yearLevel': '2',
    'phoneNumber': '09181234567',
    'status': 'Blocked',
  },
  {
    'userId': 'U003',
    'name': 'Catherine Lee',
    'email': 'catherine.lee@example.com',
    'course': 'Information Systems',
    'yearLevel': '1',
    'phoneNumber': '09192234567',
    'status': 'Active',
  },
  {
    'userId': 'U004',
    'name': 'David Kim',
    'email': 'david.kim@example.com',
    'course': 'Computer Science',
    'yearLevel': '4',
    'phoneNumber': '09201234567',
    'status': 'Blocked',
  },
  {
    'userId': 'U005',
    'name': 'Ella Torres',
    'email': 'ella.torres@example.com',
    'course': 'Information Technology',
    'yearLevel': '3',
    'phoneNumber': '09211234567',
    'status': 'Active',
  },
  {
    'userId': 'U006',
    'name': 'Frank Ramirez',
    'email': 'frank.ramirez@example.com',
    'course': 'Information Systems',
    'yearLevel': '2',
    'phoneNumber': '09221234567',
    'status': 'Blocked',
  },
  {
    'userId': 'U007',
    'name': 'Grace Liu',
    'email': 'grace.liu@example.com',
    'course': 'Computer Science',
    'yearLevel': '1',
    'phoneNumber': '09231234567',
    'status': 'Active',
  },
  {
    'userId': 'U008',
    'name': 'Henry Walker',
    'email': 'henry.walker@example.com',
    'course': 'Information Technology',
    'yearLevel': '4',
    'phoneNumber': '09241234567',
    'status': 'Blocked',
  },
  {
    'userId': 'U009',
    'name': 'Isla Chen',
    'email': 'isla.chen@example.com',
    'course': 'Information Systems',
    'yearLevel': '3',
    'phoneNumber': '09251234567',
    'status': 'Active',
  },
  {
    'userId': 'U010',
    'name': 'Jack Thompson',
    'email': 'jack.thompson@example.com',
    'course': 'Computer Science',
    'yearLevel': '2',
    'phoneNumber': '09261234567',
    'status': 'Blocked',
  },
  {
    'userId': 'U011',
    'name': 'Kyla Davis',
    'email': 'kyla.davis@example.com',
    'course': 'Information Technology',
    'yearLevel': '1',
    'phoneNumber': '09271234567',
    'status': 'Active',
  },
  {
    'userId': 'U012',
    'name': 'Liam Cruz',
    'email': 'liam.cruz@example.com',
    'course': 'Information Systems',
    'yearLevel': '4',
    'phoneNumber': '09281234567',
    'status': 'Blocked',
  },
  {
    'userId': 'U013',
    'name': 'Maya Garcia',
    'email': 'maya.garcia@example.com',
    'course': 'Computer Science',
    'yearLevel': '3',
    'phoneNumber': '09291234567',
    'status': 'Active',
  },
  {
    'userId': 'U014',
    'name': 'Nathan Lopez',
    'email': 'nathan.lopez@example.com',
    'course': 'Information Technology',
    'yearLevel': '2',
    'phoneNumber': '09301234567',
    'status': 'Blocked',
  },
  {
    'userId': 'U015',
    'name': 'Olivia Brown',
    'email': 'olivia.brown@example.com',
    'course': 'Information Systems',
    'yearLevel': '1',
    'phoneNumber': '09311234567',
    'status': 'Active',
  },
];
