name: book_ease
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  # cupertino_icons: ^1.0.2
  google_fonts: ^6.2.1
  google_nav_bar: ^5.0.7
  line_icons: ^2.0.3
    

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/logo-removebg-preview.png
    - assets/images/banner.jpg
    - assets/images/percy-book.jpg
    - assets/images/admin_logo.png
    - assets/images/lord_p.png

# flutter:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800


         

        
